from django.db import models

class Master(models.Model):
    player = models.CharField(null = True, max_length = 60, blank = True)
    birthYear = models.CharField(null = True, blank = True, max_length=40)
    birthMonth = models.CharField(null = True, blank = True, max_length=40)
    birthDay = models.CharField(null = True, blank = True, max_length=40)
    birthCountry = models.CharField(max_length = 40, blank = True, null = True)
    birthState = models.CharField(max_length = 40, blank = True, null = True)
    birthCity = models.CharField(max_length=40, blank=True, null=True)
    deathYear = models.CharField(null=True, blank = True, max_length=40)
    deathMonth = models.CharField(null=True, blank = True, max_length=40)
    deathDay = models.CharField(null=True, blank = True, max_length=40)
    deathCountry = models.CharField(max_length=40, blank = True, null = True)
    deathState = models.CharField(max_length=40, blank = True, null = True)
    deathCity = models.CharField(max_length=40, blank = True, null = True)
    nameFirst = models.CharField(max_length=40, blank = True, null = True)
    nameLast = models.CharField(max_length=40, blank = True, null = True)
    nameGiven = models.CharField(max_length = 60, blank = True, null = True)
    weight = models.CharField(null = True, blank = True, max_length=40)
    height = models.CharField(null = True, blank = True, max_length=40)
    bats = models.CharField(max_length = 30, blank = True)
    throws = models.CharField(max_length = 30, blank = True, null = True)
    debut = models.CharField(max_length = 100, blank = True, null = True)
    finalGame = models.CharField(max_length = 100, blank = True, null = True)
    retroID = models.CharField(null = True, blank = True, max_length= 50)
    bbrefID = models.CharField(null = True ,blank = True, max_length = 50)

class Batting(models.Model):
    player = models.ForeignKey(Master)
    year = models.CharField(null = True ,blank = True, max_length = 50)
    stint = models.CharField(null = True ,blank = True, max_length = 50)
    team = models.CharField(max_length = 40, blank = True, null = True)
    league = models.CharField(max_length = 40, blank = True, null = True)
    games = models.CharField(null = True ,blank = True, max_length = 50)
    at_bats = models.CharField(null = True ,blank = True, max_length = 50)
    runs = models.CharField(null = True ,blank = True, max_length = 50)
    hits = models.CharField(null = True ,blank = True, max_length = 50)
    doubles = models.CharField(null = True ,blank = True, max_length = 50)
    triples = models.CharField(null = True ,blank = True, max_length = 50)
    home_runs = models.CharField(null = True ,blank = True, max_length = 50)
    rbi = models.CharField(null = True ,blank = True, max_length = 50)
    stolen_bases = models.CharField(null = True ,blank = True, max_length = 50)
    caught_stealing = models.CharField(null = True ,blank = True, max_length = 50)
    walks = models.CharField(null = True ,blank = True, max_length = 50)
    strikeouts = models.CharField(null = True ,blank = True, max_length = 50)
    intentional_walks = models.CharField(null = True ,blank = True, max_length = 50)
    hit_by_pitch = models.CharField(null = True ,blank = True, max_length = 50)
    sac_hits = models.CharField(null = True ,blank = True, max_length = 50)
    sac_flies = models.CharField(null = True ,blank = True, max_length = 50)
    double_plays = models.CharField(null = True ,blank = True, max_length = 50)

class Fielding(models.Model):
    player = models.ForeignKey(Master)
    year = models.CharField(null = True ,blank = True, max_length = 50)
    stint = models.CharField(null = True ,blank = True, max_length = 50)
    team = models.CharField(max_length = 40, blank = True)
    league = models.CharField(max_length = 40, blank = True)
    position = models.CharField(max_length = 50, blank = True)
    games = models.CharField(null = True ,blank = True, max_length = 50)
    games_started = models.CharField(null = True ,blank = True, max_length = 50)
    innOuts = models.CharField(null = True ,blank = True, max_length = 50)
    put_outs = models.CharField(null = True ,blank = True, max_length = 50)
    assists = models.CharField(null = True ,blank = True, max_length = 50)
    double_plays = models.CharField(null = True ,blank = True, max_length = 50)
    passed_balls = models.CharField(null = True ,blank = True, max_length = 50)
    wild_pitches = models.CharField(null = True ,blank = True, max_length = 50)
    stolen_bases = models.CharField(null = True ,blank = True, max_length = 50)
    caught_stealing = models.CharField(null = True ,blank = True, max_length = 50)
    zone = models.CharField(null = True ,blank = True, max_length = 50)

class Pitcher(models.Model):
    player = models.ForeignKey(Master)
    year = models.CharField(null = True ,blank = True, max_length = 50)
    stint = models.CharField(null = True ,blank = True, max_length = 50)
    team = models.CharField(max_length = 40, blank = True)
    league = models.CharField(max_length = 40, blank = True)
    wins = models.CharField(null = True ,blank = True, max_length = 50)
    losses = models.CharField(null = True ,blank = True, max_length = 50)
    games = models.CharField(null = True ,blank = True, max_length = 50)
    games_started = models.CharField(null = True ,blank = True, max_length = 50)
    complete_games = models.CharField(null = True ,blank = True, max_length = 50)
    shutouts = models.CharField(null = True ,blank = True, max_length = 50)
    saves = models.CharField(null = True ,blank = True, max_length = 50)
    outs_pitched = models.CharField(null = True ,blank = True, max_length = 50)
    hits = models.CharField(null = True ,blank = True, max_length = 50)
    earned_runs = models.CharField(null = True ,blank = True, max_length = 50)
    home_runs = models.CharField(null = True ,blank = True, max_length = 50)
    walks = models.CharField(null = True ,blank = True, max_length = 50)
    strikeouts = models.CharField(null = True ,blank = True, max_length = 50)
    opponent_avg = models.CharField(null = True ,blank = True, max_length = 50)
    era = models.CharField(null = True ,blank = True, max_length = 50)
    intentional_bb = models.CharField(null = True ,blank = True, max_length = 50)
    wild_pitches = models.CharField(null = True ,blank = True, max_length = 50)
    hit_by_pitch = models.CharField(null = True ,blank = True, max_length = 50)
    balks = models.CharField(null = True ,blank = True, max_length = 50)
    batters_faced = models.CharField(null = True ,blank = True, max_length = 50)
    games_finised = models.CharField(null = True ,blank = True, max_length = 50)
    runs = models.CharField(null = True ,blank = True, max_length = 50)
    sac_against = models.CharField(null = True ,blank = True, max_length = 50)
    sac_flies = models.CharField(null = True ,blank = True, max_length = 50)
    ground_dp_against = models.CharField(null = True ,blank = True, max_length = 50)
