# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthYear', models.IntegerField()),
                ('birthMonth', models.IntegerField(max_length=30)),
                ('birthDay', models.IntegerField()),
                ('birthCountry', models.CharField(max_length=40)),
                ('birthState', models.CharField(max_length=40)),
                ('birthCity', models.CharField(max_length=40)),
                ('deathYear', models.IntegerField(null=True)),
                ('deathMonth', models.IntegerField(null=True)),
                ('deathDay', models.IntegerField(null=True)),
                ('deathCountry', models.CharField(max_length=40, null=True)),
                ('deathState', models.CharField(max_length=40, null=True)),
                ('deathCity', models.CharField(max_length=40, null=True)),
                ('nameFirst', models.CharField(max_length=40)),
                ('nameLast', models.CharField(max_length=40)),
                ('nameGiven', models.CharField(max_length=60)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('bats', models.CharField(max_length=30)),
                ('throws', models.CharField(max_length=30)),
                ('debut', models.CharField(max_length=100)),
                ('finalGame', models.CharField(max_length=100)),
                ('retroID', models.IntegerField()),
                ('bbrefID', models.IntegerField()),
            ],
        ),
    ]
