# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(null=True)),
                ('stint', models.IntegerField(null=True)),
                ('team', models.CharField(blank=True, max_length=40)),
                ('league', models.CharField(blank=True, max_length=40)),
                ('games', models.IntegerField(null=True)),
                ('at_bats', models.IntegerField(null=True)),
                ('runs', models.IntegerField(null=True)),
                ('hits', models.IntegerField(null=True)),
                ('doubles', models.IntegerField(null=True)),
                ('triples', models.IntegerField(null=True)),
                ('home_runs', models.IntegerField(null=True)),
                ('rbi', models.IntegerField(null=True)),
                ('stolen_bases', models.IntegerField(null=True)),
                ('caught_stealing', models.IntegerField(null=True)),
                ('walks', models.IntegerField(null=True)),
                ('strikeouts', models.IntegerField(null=True)),
                ('intentional_walks', models.IntegerField(null=True)),
                ('hit_by_pitch', models.IntegerField(null=True)),
                ('sac_hits', models.IntegerField(null=True)),
                ('sac_flies', models.IntegerField(null=True)),
                ('double_plays', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fielding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(null=True)),
                ('stint', models.IntegerField(null=True)),
                ('team', models.CharField(blank=True, max_length=40)),
                ('league', models.CharField(blank=True, max_length=40)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('games', models.IntegerField(null=True)),
                ('games_starteds', models.IntegerField(null=True)),
                ('innOuts', models.IntegerField(null=True)),
                ('put_outs', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('double_plays', models.IntegerField(null=True)),
                ('passed_balls', models.IntegerField(null=True)),
                ('wild_pitches', models.IntegerField(null=True)),
                ('stolen_bases', models.IntegerField(null=True)),
                ('caught_stealing', models.IntegerField(null=True)),
                ('zone', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(null=True)),
                ('stint', models.IntegerField(null=True)),
                ('team', models.CharField(blank=True, max_length=40)),
                ('league', models.CharField(blank=True, max_length=40)),
                ('wins', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('games', models.IntegerField(null=True)),
                ('games_started', models.IntegerField(null=True)),
                ('complete_games', models.IntegerField(null=True)),
                ('shutouts', models.IntegerField(null=True)),
                ('saves', models.IntegerField(null=True)),
                ('outs_pitched', models.FloatField(null=True)),
                ('hits', models.IntegerField(null=True)),
                ('earned_runs', models.IntegerField(null=True)),
                ('home_runs', models.IntegerField(null=True)),
                ('walks', models.IntegerField(null=True)),
                ('strikeouts', models.IntegerField(null=True)),
                ('opponent_avg', models.FloatField(null=True)),
                ('era', models.FloatField(null=True)),
                ('intentional_bb', models.IntegerField(null=True)),
                ('wild_pitches', models.IntegerField(null=True)),
                ('hit_by_pitch', models.IntegerField(null=True)),
                ('balks', models.IntegerField(null=True)),
                ('batters_faced', models.IntegerField(null=True)),
                ('games_finised', models.IntegerField(null=True)),
                ('runs', models.IntegerField(null=True)),
                ('sac_against', models.IntegerField(null=True)),
                ('sac_flies', models.IntegerField(null=True)),
                ('ground_dp_against', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='player',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='bats',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='master',
            name='bbrefID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='birthCity',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='master',
            name='birthCountry',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='master',
            name='birthDay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='birthMonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='birthState',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='master',
            name='birthYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='deathCity',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='deathCountry',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='deathState',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='debut',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='master',
            name='finalGame',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='master',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='nameFirst',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='master',
            name='nameGiven',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='master',
            name='nameLast',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='master',
            name='retroID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='throws',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='master',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Master'),
        ),
        migrations.AddField(
            model_name='fielding',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Master'),
        ),
        migrations.AddField(
            model_name='batting',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Master'),
        ),
    ]
