# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20161026_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='birthDay',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='birthMonth',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='birthYear',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='deathDay',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='deathMonth',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='deathYear',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='height',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='weight',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
