# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_auto_20161026_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='league',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='team',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
