# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_auto_20161026_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fielding',
            old_name='games_starteds',
            new_name='games_started',
        ),
        migrations.RenameField(
            model_name='fielding',
            old_name='Year',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='pitcher',
            old_name='Year',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='fielding',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='era',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='opponent_avg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
